# Generated by Django 3.2.11 on 2022-01-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EjeTematico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.area')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=4)),
                ('año_inicio_generacion', models.IntegerField(default=2022)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('opcionA', models.CharField(max_length=100)),
                ('opcionB', models.CharField(max_length=100)),
                ('opcionC', models.CharField(max_length=100)),
                ('opcionD', models.CharField(max_length=100)),
                ('opcionCorrecta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('ejeTematico', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.ejetematico')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=35)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=9)),
                ('grupo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.grupo')),
            ],
        ),
    ]
