# Generated by Django 4.0.5 on 2022-06-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_evaluacionprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionprocess',
            old_name='titulo',
            new_name='comentarios',
        ),
    ]
