# Generated by Django 4.0.5 on 2022-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_rename_titulo_evaluacionprocess_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionprocess',
            old_name='comentarios',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='evaluacionprocess',
            name='cantidadPreguntas',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
