# Generated by Django 4.0.5 on 2022-06-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_rename_comentarios_evaluacionprocess_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionprocess',
            name='fecha',
        ),
    ]
