# Generated by Django 4.0.5 on 2022-06-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_remove_evaluacionprocess_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionprocess',
            name='cantidadPreguntas',
            field=models.IntegerField(),
        ),
    ]
