# Generated by Django 4.0.5 on 2022-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_alter_evaluacionprocess_cantidadpreguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionprocess',
            name='cantidadPreguntas',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('5', '5')], max_length=9),
        ),
    ]
