# Generated by Django 4.0.5 on 2022-06-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_alter_evaluacionprocess_cantidadpreguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionprocess',
            name='cantidadPreguntas',
        ),
    ]
