# Generated by Django 4.0.5 on 2022-06-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_remove_evaluacionprocess_cantidadpreguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionprocess',
            name='ejeTematico',
        ),
    ]
