# Generated by Django 4.0.5 on 2022-06-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_remove_evaluacionprocess_ejetematico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionprocess',
            name='grupo',
        ),
    ]
